## SKG
## Plot agents generated by catalyst
## January 27, 2018


library(reshape2)
library(ggplot2)

df <- read.csv("agents-out.csv", header = FALSE)
df <- df[, -11] # get rid of the empty row. should fix in write agents
colnames(df) <- paste0("Agent-", 1:10)
df$t <- 0:(nrow(df)-1)



df_melt <- melt(df, id.vars = "t")
df_melt$status = factor(df_melt$value,
                        levels = 2:0,
                        labels =rev(c("Susceptible", "Infectious", "Recovered")))

## My custom ggplot background
my_theme <-  theme_bw() + theme(
    axis.text.x = element_text(size = 14, family = "Palatino"),
    axis.text.y= element_text(size = 14, family = "Palatino"),
    axis.title.x= element_text(size = 18, family = "Palatino"),
    axis.title.y= element_text(size = 18, family = "Palatino"),
    plot.title = element_text(size = 24, family = "Palatino"),
    legend.title = element_text(size = 20, family = "Palatino"),
    legend.text = element_text(family = "Palatino", size = 16),
    legend.key.size = unit(3, "line"),
    plot.subtitle=element_text(size=16, family = "Palatino"),
    strip.text.y = element_text(angle = 0, family = "Palatino", size = 12),
    strip.background=element_rect(fill = "white")
)


ggplot(data = df_melt,
       aes( x= t, y = status, col = status)) +
    geom_point() + geom_line() +
    facet_grid(variable ~ .) +
    theme(strip.text.y = element_text(angle = 0)) +
    my_theme + 
    scale_color_manual(name = "Compartment",
                         values = rev(c("blue", "darkred", "springgreen4"))) +
    labs(title = "Agent compartment over time",
         x= "Time", y = "Compartment")

ggsave("agents-plot.pdf")
